import React, { useState, useEffect } from 'react';
import { aiService } from '../services/api';
import { useToast } from '../context/ToastContext';
import Loader from '../components/common/Loader';
import { 
  Sparkles, 
  Bot, 
  CheckCircle2, 
  AlertTriangle, 
  Lightbulb, 
  History, 
  Award, 
  ArrowRight, 
  RefreshCw 
} from 'lucide-react';

const AIAdvisor = () => {
  const { addToast } = useToast();
  const [loading, setLoading] = useState(true);
  const [analyzing, setAnalyzing] = useState(false);
  const [report, setReport] = useState(null);
  const [history, setHistory] = useState([]);

  useEffect(() => {
    fetchAIReports();
  }, []);

  const fetchAIReports = async () => {
    setLoading(true);
    try {
      const res = await aiService.getReports();
      if (res.data.success && res.data.data.length > 0) {
        setHistory(res.data.data);
        setReport(res.data.data[0].report);
      }
    } catch (err) {
      addToast('Failed to load past AI advisory reports.', 'error');
    } finally {
      setLoading(false);
    }
  };

  const handleRunAnalysis = async () => {
    setAnalyzing(true);
    try {
      const res = await aiService.analyze();
      if (res.data.success) {
        setReport(res.data.data);
        addToast('Fresh AI Financial Report generated successfully!', 'success');
        fetchAIReports();
      }
    } catch (err) {
      addToast('Failed to generate AI report.', 'error');
    } finally {
      setAnalyzing(false);
    }
  };

  if (loading) {
    return <Loader text="Loading AI Financial Advisor Hub..." />;
  }

  return (
    <div className="space-y-6">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-emerald-500 animate-pulse" /> AI Advisor Hub
          </h1>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Personalized advisory generated by Google Gemini AI SDK using your live financial data
          </p>
        </div>

        <button
          onClick={handleRunAnalysis}
          disabled={analyzing}
          className="px-6 py-3 rounded-xl gradient-bg text-white font-bold text-sm shadow-xl shadow-emerald-500/20 hover:scale-105 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
        >
          {analyzing ? (
            <>
              <RefreshCw className="w-4 h-4 animate-spin" /> Analyzing Financial Telemetry...
            </>
          ) : (
            <>
              <Bot className="w-4 h-4" /> Run Gemini AI Analysis
            </>
          )}
        </button>
      </div>

      {/* Main Active Report View */}
      {report ? (
        <div className="space-y-6">
          
          {/* Top Score Banner */}
          <div className="glass-card p-6 sm:p-8 flex flex-col md:flex-row items-center justify-between gap-6 border-emerald-500/30">
            <div className="flex items-center gap-6">
              <div className="relative w-24 h-24 rounded-full bg-emerald-500/10 border-4 border-emerald-500/30 flex items-center justify-center shrink-0">
                <div className="text-center">
                  <div className="text-3xl font-black text-emerald-500 leading-none">
                    {report.financialHealthScore}
                  </div>
                  <div className="text-[10px] uppercase font-bold text-slate-400 mt-0.5">Score</div>
                </div>
              </div>

              <div>
                <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-500 text-xs font-bold uppercase tracking-wider mb-1">
                  <Award className="w-3.5 h-3.5" /> Financial Health Rating
                </div>
                <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                  {report.financialHealthScore >= 80 ? 'Excellent Status' : report.financialHealthScore >= 60 ? 'Stable Position' : 'Action Required'}
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 max-w-md">
                  {report.summary}
                </p>
              </div>
            </div>

            <div className="w-full md:w-auto p-4 rounded-xl bg-slate-50 dark:bg-slate-800/50 text-xs space-y-2 text-left">
              <div>
                <span className="text-slate-400">Highest Expense Category:</span>
                <span className="font-bold text-rose-500 ml-1.5">{report.highestExpenseCategory || 'N/A'}</span>
              </div>
              <div>
                <span className="text-slate-400">Budget Status:</span>
                <span className="font-bold text-slate-900 dark:text-white ml-1.5">{report.budgetAdvice ? 'Evaluated' : 'N/A'}</span>
              </div>
            </div>
          </div>

          {/* Grid: Saving Tips & Monthly Insights */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            {/* Actionable Saving Tips */}
            <div className="glass-card p-6 space-y-4">
              <h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <Lightbulb className="w-5 h-5 text-amber-500" /> Actionable Saving Opportunities
              </h3>
              <div className="space-y-3">
                {report.savingTips && report.savingTips.map((tip, idx) => (
                  <div key={idx} className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/40 text-xs text-slate-700 dark:text-slate-200 flex items-start gap-2.5">
                    <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                    <span>{tip}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Monthly Insights */}
            <div className="glass-card p-6 space-y-4">
              <h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <Bot className="w-5 h-5 text-cyan-500" /> Key Financial Insights
              </h3>
              <div className="space-y-3">
                {report.monthlyInsights && report.monthlyInsights.map((insight, idx) => (
                  <div key={idx} className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/40 text-xs text-slate-700 dark:text-slate-200 flex items-start gap-2.5">
                    <Sparkles className="w-4 h-4 text-cyan-500 shrink-0 mt-0.5" />
                    <span>{insight}</span>
                  </div>
                ))}
              </div>
            </div>

          </div>

          {/* Motivational Advice Banner */}
          {report.motivation && (
            <div className="p-5 rounded-2xl bg-gradient-to-r from-emerald-500/10 via-teal-500/5 to-cyan-500/10 border border-emerald-500/20 text-center text-sm font-semibold text-slate-800 dark:text-slate-200 italic">
              "{report.motivation}"
            </div>
          )}

        </div>
      ) : (
        <div className="glass-card p-12 text-center max-w-xl mx-auto space-y-4">
          <Bot className="w-16 h-16 text-emerald-500 mx-auto animate-bounce" />
          <h3 className="text-xl font-bold text-slate-900 dark:text-white">No AI Analysis Report Found</h3>
          <p className="text-sm text-slate-500 dark:text-slate-400">
            Click the "Run Gemini AI Analysis" button above to evaluate your income, expenses, and budget telemetry.
          </p>
        </div>
      )}

      {/* Report History */}
      {history.length > 0 && (
        <div className="glass-card p-6 space-y-4">
          <h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <History className="w-5 h-5 text-slate-500" /> Historical Analysis Archive
          </h3>
          <div className="divide-y divide-slate-100 dark:divide-slate-800">
            {history.map((item, idx) => (
              <div key={item.id || idx} className="py-3 flex items-center justify-between text-xs">
                <div>
                  <span className="font-semibold text-slate-900 dark:text-white">Report #{history.length - idx}</span>
                  <span className="text-slate-400 ml-2">({new Date(item.created_at).toLocaleString()})</span>
                </div>
                <div className="font-bold text-emerald-500">
                  Score: {item.report?.financialHealthScore || 'N/A'}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

    </div>
  );
};

export default AIAdvisor;
